# Generated by Django 6.0.8 on 2026-08-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
